name: Dogs 🐕

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  aCatForCreatingThePullRequest:
    name: A dog for your effort!
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: stanleynguyen/action-dogs@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
