ramsey-gififier:
  name: Ramsey GIFifier
  on:
    # Run this workflow only when a new pull request is opened
    # compare: https://git.io/JvTyV
    pull_request:
      types: [opened]
  runs-on: ubuntu-latest
  steps:
  - name: Ramsey GIFifier
    uses: ethan-dowler/ramsey-gififier@master
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}