name: Ramsey GIFifier

on:
  pull_request:
    types: [opened]

jobs:
  ramsey-gififier:
    name: Ramsey GIFifier
    runs-on: ubuntu-latest
    steps:
    - name: Ramsey GIFifier
      uses: ethan-dowler/ramsey-gififier@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
