name: Test

on:
  push:
    branches: [ConverterAscii]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Test with Go
      run: go test -json > TestResults-1.19.json
    
    - name: Upload Go test results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results-1.19
        path: TestResults-1.19.json
