name: Test

on:
  push:
    branches: [ConverterAscii]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...


    - name: Save test results
    command: |
      mkdir -p ~/test-results/junit/
      find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
    when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

    - name: Publish test results
    uses: actions/upload-artifact@v2
    with:
      name: test-results
      path: test-results

    - name: Deploy test result
    uses: JamesIves/github-pages-deploy-action@4.1.2
    with:
      branch: gh-pages
      folder: test-results
      clean: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
