name: Test

on:
  push:
    branches: [ConverterAscii]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Test with Go
      run: go test -coverprofile=coverage.out
      
    - name: Produce coverage report
      run: go tool cover -html=coverage.out -o testResults/coverage.html
